### ISSUE TITLE
下拉增加上面那个div高度的问题

### ISSUE THREAD

**Issue by mcfly001** [Alex-fun/vue-list#3]
下拉滚动的时候我给最上面的div设置的高度为一次加载出来元素的高度，但是发现scrollTop也增加了相应的高度，这样判断条件就一直成立就变成死循环了，请问怎么解决？

**Comment by hejianxian** [comment]
@mcfly001 你好！

首先，你说的最上面的div，是指撑开高度的顶部div吗？然后这里的一个概念就是，列表的总高度是不变的，如果加载更多元素后，列表总高度变了，但是理论上scrollTop不需要改变，只有发生滚动的时候才从新计算。

目前这个demo是有bug的，一直没时间改，抱歉。

**Comment by mcfly001** [comment]
你好，我说的高度就是最上面的div，后来我改成了给ul设置padding-top就可以了，我现在的做法是下拉的时候去加载，然后在nextTick里面把最上面的10条数据减去（假设每次加载10个），然后增加ul的padding-top为这10条数据的高度，这样就可以了，之前我设置了一个空的div，然后给这个空的div设置高度会发现一直加载,原因是我的判断条件有问题，我是把scrollTop-lastajax > _scrollHeight -5 && self.isload 作为判断条件，其中scrollTop为滚动条滚动距离，lastajax为上次加载的y轴位置，_scrollHeight为加载的条数据的高度，如果我给最上层的div设置了高度会导致scrollTop的值也会同步增加，导致判断条件一直成立，现在改为padding-top就可以了，这个需求困扰了我2天了，看到你的文章给了我思路，非常感谢你的付出。案例上第三次下拉到最低的时候会触发多次加载，希望有时间能修改一下，谢谢

**Comment by hejianxian** [comment]
好的！谢谢你的反馈！
