### ISSUE TITLE
向上或者向下滑动的时候，组件会自动滑动到最顶部或最底部

### ISSUE THREAD

**Issue by shanminlv** [Alex-fun/vue-list#4]
经过研究是滑动加载新数据时，判断的条件不太对，this.lastScrollTop === null || Math.abs(_scrollTop - this.lastScrollTop) > this._max 和 this.to === this.list.length && _height - _scrollTop - _contentHeight < this.distance，因为是scroll事件所以会不断地触发

**Comment by hejianxian** [comment]
@shanminlv 

谢谢你的反馈！我会找个时间修改这些bug，并且加入一些新的功能！😁
